version: "3.9"

networks:
  netapp_net: {}

services:
  stream-api:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: stream-api
    environment:
      - API_PORT=8001
    ports: ["8001:8001"]
    command: ["uvicorn", "api.server:app", "--host", "0.0.0.0", "--port", "8001"]
    networks: ["netapp_net"]

  stream-producer:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: stream-producer
    environment:
      - KAFKA_BOOTSTRAP=netapp-kafka:29092
      - KAFKA_TOPIC=sensor_stream
    command: ["python", "-m", "streaming.producer.producer"]
    networks: ["netapp_net"]
    depends_on: ["stream-api"]

  stream-consumer:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: stream-consumer
    environment:
      - KAFKA_BOOTSTRAP=netapp-kafka:29092
      - KAFKA_TOPIC=sensor_stream
      - KAFKA_GROUP=netapp-consumer
      - STREAM_API=http://stream-api:8001
      - ANOMALY_Z_THRESH=3.0
    command: ["python", "-m", "streaming.consumer.consumer"]
    networks: ["netapp_net"]
    depends_on: ["stream-api"]

  stream-ui:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: stream-ui
    environment:
      - STREAM_API=http://localhost:8001
    ports: ["8601:8601"]
    command: ["streamlit", "run", "/app/ui/stream_dashboard.py", "--server.port", "8601", "--server.address", "0.0.0.0"]
    networks: ["netapp_net"]
    depends_on: ["stream-api"]
